### PR TITLE
ROS-I driver for 6-axis Staubli robots

### PR DESCRIPTION
**Pull request by MuriloMartins**
Introducing the ROS-Industrial driver (server side) for 6-axis Staubli robots, implemented in VAL3.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR! :tada:

I noticed that some of the earlier commits don't get attributed to your account. Is that something you'd like to fix before we merge this?

**Comment by MuriloMartins** [comment]
huummm... maybe I should, for consistency.

**Comment by gavanderhoorn** [comment]
Also: the description and the `README.md` explicitly say "for 6-axis" robots. Is that really an assumption in the driver itself? Or is it just that you haven't tested it with anything else (ie: 4 axis scara)?

**Comment by gavanderhoorn** [comment]
You should be able to do that with some interactive rebasing, or with `git filter-branch`.

**Comment by MuriloMartins** [comment]
Regarding 6-axis robots, it's not an assumption, it's an assertion. ;-)
It will not work with 4-axis scara robots because I convert joint positions from ROS messages to VAL3's `jointRx` type, which is exclusive to 6-axis robots, as opposed to `jointRs` for 4-axis scara robots.

Parts of the code using the `jointRx` type also assume that an array containing joint positions (from ROS messages) would have at least 6 elements, rather than 4 (for the message ID 14 which has an array of 10 joint positions, the last 4 are ignored).

**Comment by MuriloMartins** [comment]
I suppose it would be possible to make it compatible with scara robots and it wouldn't be too difficult to apply the changes.

That said, I suppose we should first create `_support` and potentially `_gazebo` packages for at least one scara model before we change, test and announce this driver as 4-axis scara-compatible. Does that make sense?

**Comment by gavanderhoorn** [comment]
> That said, I suppose we should first create `_support` and potentially `_gazebo` packages for at least one scara model before we change, test and announce this driver as 4-axis scara-compatible. Does that make sense?

Yes. It's clearly stated in multiple places, so it's fine.

I was just curious as to the reason why.

**Comment by gavanderhoorn** [comment]
Do you intend to fixup the commit author info? In that case I'll post-pone merging.

Just force-push to the same branch once your done.

**Comment by MuriloMartins** [comment]
Yes, I'm doing that now... I'll let you know! :-)

**Comment by MuriloMartins** [comment]
@gavanderhoorn done!

**Comment by MuriloMartins** [comment]
I wrote a Python script to add the license header to all `*.pgx` files. The `*.pjx` and `*.dtx` files are still missing the license information.

**Comment by gavanderhoorn** [comment]
@MuriloMartins: sorry for not merging yesterday, I had to go out.

Thanks for adding the license headers.

One thing I just now noticed though: the `val3_server-devel` branch is an orphan (not completely, but a large part of the commits): it does not start from a commit that is currently part of the respository. This is probably a result of you importing the gitlab branch.

It'd be nice if we can somehow reattach this, to make the history a bit saner. Let's see how we can do that with the least amount of effort.

**Comment by gavanderhoorn** [comment]
@MuriloMartins: a bit more effort than I first thought, but I think it turned out pretty ok. See [gavanderhoorn/val3_server-devel_merge_candidate](https://github.com/gavanderhoorn/staubli_experimental/tree/val3_server-devel_merge_candidate) (comparison [here](https://github.com/ros-industrial/staubli_experimental/compare/indigo-devel...gavanderhoorn:val3_server-devel_merge_candidate)).

It's basically your commits, but made to appear to start out as a branch from `indigo-devel` and some minor cleanups / changes (removing `#` from commit msgs, injecting two commits from me (pkging related) and push all VAL3 related changes down into `staubli_val3_driver/val3` from the first commit). Provenance of all changes is completely preserved.

If you are ok with this, you could fetch the branch to your clone and then force push it 'over' the current `val3_server-devel`. That should update this PR.

**Comment by MuriloMartins** [comment]
@gavanderhoorn, I followed your suggestion. Thanks for sorting that out!

**Comment by gavanderhoorn** [comment]
Great. I'll fix Travis and then we can merge.

**Comment by gavanderhoorn** [comment]
I'm going to ignore Travis for this one. I've tested locally and all tests (still) pass.

**Comment by gavanderhoorn** [comment]
Thanks @MuriloMartins for this :100:, really appreciate the effort :+1:.

I'll create issues for a few outstanding things, but we'll merge this as-is.

**Comment by gavanderhoorn** [comment]
:beers:

**Comment by MuriloMartins** [comment]
Hi @gavanderhoorn, no worries!

I'll be happy to address forthcoming issues, bugs and feature requests, as we might also benefit from them! :-)

**Pull request merged**
