### PR TITLE
Tx90 and Rx160 update

### PR DESCRIPTION
**Pull request by nilsmelchert**
Updated some deprecated syntax and the urdf files for the tx90 .

### CODE REVIEW

**Comment by nilsmelchert** [comment]
Wait before you review. I forgot about adjusting the `staubli_rx160_gazebo` package. I will do a couple of changes and push them to the branch of this PR.

**Comment by gavanderhoorn** [comment]
A nice PR again, thanks for this.

Could I ask you to squash all TX90 changes into a single commit (or two: seperate ones for the support and Gazebo pkgs), as you did for the RX160?

You can use a `rebase` for this, and then force push to your `tx90_update`.

**Comment by gavanderhoorn** [comment]
If we really want to be strict about it, this branch (`tx90_update`) should not contain commits that touch `rx160` files.

**Comment by nilsmelchert** [comment]
> If we really want to be strict about it, this branch (tx90_update) should not contain commits that touch rx160 files.

Totally true. I wasn't thinking about changing anything for the rx160 series, when I created that branch. Are you still ok with the name or do you want me to create another branch with a different name, that mentioned both packages?

**Comment by nilsmelchert** [comment]
> Could I ask you to squash all TX90 changes into a single commit (or two: seperate ones for the support and Gazebo pkgs), as you did for the RX160?

Sure, I'll do that.

**Comment by nilsmelchert** [comment]
Was that ok? I have never squashed multiple commits into one before.

**Comment by gavanderhoorn** [comment]
Well, yes, the squash was successful, but now we have only a single commit.

I was thinking we would reduce everything to three commits, but we can work with this.

**Comment by gavanderhoorn** [comment]
The changes are ok in principle.

Would you want me to wait for you to split them up into separate commits again?

Otherwise I'll merge tomorrow.

**Comment by nilsmelchert** [comment]
> Would you want me to wait for you to split them up into separate commits again?

No that is ok for now. Ill consider making seperate commits for my next PR. Is that ok for you? And aren't the commits, that i squashed by rebasing interactively lost anyways?

> Otherwise I'll merge tomorrow.

So yes, that would be nice.

**Comment by nilsmelchert** [comment]
> The changes are ok in principle.

If I forgot to update something, just let me know. I am always open to suggestions and willing to learn.

**Comment by gavanderhoorn** [comment]
@nilsmelchert wrote:
> And aren't the commits, that i squashed by rebasing interactively lost anyways?

no, you can still get them back using the git `reflog`.

**Comment by nilsmelchert** [comment]
> no, you can still get them back using the git reflog.

I just had a look at the commits that I squashed. I think it would be very confusing to separate them, cleanly.

I would propose to just merge the PR if that is ok with you.

**Comment by nilsmelchert** [comment]
I just tried to revert the rebase using `reflog` and `reset` but I somehow can't find the commit to the state before the rebase anymore.
Sorry, I am not very experienced with this.

The reason could be, that I am working on my private computer and not the one I did the Rebase with.

**Comment by gavanderhoorn** [comment]
You don't need to do anything any more. I just wanted to make you aware of the `reflog`.

**Comment by nilsmelchert** [comment]
Ok. Thanks again for reviewing.

**Comment by nilsmelchert** [comment]
Are you going to merge it?

**Comment by nilsmelchert** [comment]
I could also close this PR are do the update again. It wasn't that much work and it could definitely do it again.

Sorry if I am causing any inconveniences.

**Comment by gavanderhoorn** [comment]
No need. I just need to find some time to merge it.

I :+1: your enthusiasm btw, I apologise for taking so long.

**Comment by nilsmelchert** [comment]
Thank you very much.

**Comment by gavanderhoorn** [comment]
@nilsmelchert: as the changes to the Gazebo pkgs cannot be made bw-compatible (`roslaunch` in Indigo doesn't have the capabilities for that), I've reverted those changes in your PR.

This way we can at least get the fixes for all the other things (xacros and launch files) merged in Indigo as well. Then I'll branch Kinetic and we can reintroduce the fixes for Kinetic+ `ros_control`/Gazebo.

**Comment by gavanderhoorn** [comment]
Thanks again for the contributions @nilsmelchert, much appreciated. :beers: 

And my apologies for taking so long to merge them. Unfortunately I had some other matters to attend to.

**Comment by nilsmelchert** [comment]
> Then I'll branch Kinetic and we can reintroduce the fixes for Kinetic+ ros_control/Gazebo.

I did another PR #24 to reintroduce the fixes for the `kinetic-devel` branch.

**Pull request merged**
