### PR TITLE
Decimate all TX90 meshes (and redo collision meshes)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Even though I'd decimated them in #5, they were still 11 MB in total, which is a bit much.

I've decimated them further and now approx 4 MB remains.

No functional changes.

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by nilsmelchert** [comment]
Is there a reason why we do not use collada (.dae) format for visual meshes?
In my opinion, it would improve the appearance a lot.

**Comment by gavanderhoorn** [comment]
They simply weren't created for #5 and I don't have the time to do it myself.

This PR *only* decimates what's there, it doesn't change anything else.

**Comment by gavanderhoorn** [comment]
Thanks for the review @Levi-Armstrong :+1: appreciated.

**Comment by gavanderhoorn** [comment]
@nilsmelchert: if you see a chance to create proper Collada meshes (so with colouring and/or textures) and are willing to contribute that would be very much appreciated.

Collada meshes without proper texturing or vertex colours don't improve appearance.

**Pull request merged**
